version: "3.8"
services:
  node_app:
    container_name: node_app
    build: .
    image: neel23/crud_demo
    ports:
      - "3000:3000"
    environment:
      - DB_DATABASE="Docker_Practise"
      - DB_USER="postgres"
      - DB_PASSWORD="Neel@232003"
      - DB_HOST="node_db"
    restart: always
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Neel@232003
    volumes:
      - node_db_data:/var/lib/postgresql/data
volumes:
  node_db_data: {}
